var stickersList = {
  'hap': {
    '1kki': 'pose',
    '1kkn': 'prof',
    '1kkh': 'ananas',
    '1kkl': 'plage',
    '1kkm': 'onche',
    '1kkk': 'pls2',
    '1kkg': 'flaque',
    '1kkj': 'btg2',
  },
  'noel': {
    '1kks': 'pls',
    '1kkq': 'continue',
    '1kkt': 'haha',
    '1kkp': 'nudiste',
    '1kku': 'panache',
    '1kkr': 'bonnet',
    '1kkv': 'btg',
    '1kko': 'masque',
  },
  'bridgely': {
    '1jnj': 'billets',
    '1jnc': 'hahaha',
    '1jnh': 'perplexe',
    '1jng': 'furie',
    '1jnf': 'cigare',
    '1jni': 'dehors2',
    '1jne': 'hein',
    '1jnd': 'malin',
  },
  'lamasticot': {
    '1kgx': 'emo',
    '1kh1': 'laser',
    '1kgz': 'jesus',
    '1kgv': 'racaille',
    '1kgw': 'btg3',
    '1kgy': 'couronne',
    '1kgu': 'flamme',
    '1kh0': 'pls3',
  },
  'grukk': {
    '1lgd': 'fort',
    '1lgc': 'question2',
    '1lgf': 'combat',
    '1lgb': 'grogne',
    '1lgh': 'grukk',
    '1lgg': 'hun',
    '1lga': 'trance',
    '1lge': 'pouce',
  },
  'bud': {
    'zu6': 'oklm',
    '1f8e': 'oklm2',
    '1f89': 'poker',
    'zuc': '+2',
    'zu2': 'hahah',
    '1f8a': 'dur',
    'zub': 'hin',
    'zua': 'zzz',
    'zu9': 'grr',
    'zu8': 'oh',
    '1f8d': 'argh',
    '1f8b': '5min',
    '1f8f': 'bbq',
    '1f88': 'sup',
    'zu7': 'burp',
    '1f8c': 'colis',
  },
  'domdevill': {
    '1ljl': 'chevalier',
    '1ljj': 'hop',
    '1ljm': 'bide',
    '1ljn': 'photo',
    '1ljo': 'bescherelle',
    '1ljp': '+1',
    '1ljr': 'master',
    '1ljq': 'thug',
  },
  'duracell': {
    '1jc3-fr': 'salut2',
    '1jc5': 'love',
    '1li5': 'gg',
    '1leb': 'tchin',
    '1jcg': 'jmec',
    '1jch': 'hahaha2',
    '1li4': 'star',
    '1jcl': 'aide',
    '1leq-fr': 'vacances',
    '1lej-fr': 'joel',
    '1li3': 'ba',
  },
  'rex-ryder': {
    '1lmd': 'boom',
    '1lmb': 'hahaha3',
    '1lm9': 'ok2',
    '1lmf': 'burger',
    '1lmc': 'deprime',
    '1lme': 'regard',
    '1lmg': 'chasse',
    '1lma': 'attaque',
  },
  'saumonarcenciel': {
    '1lmj': 'pote',
    '1lmk': 'triste',
    '1lmh': 'cute2',
    '1lmi': 'sombrero',
    '1lml': 'sleep2',
    '1lmm': 'hotte',
    '1lmo': 'titeuf',
    '1lmp': 'wc',
    '1lmn': 'hey',
    '1mqv': 'magie',
    '1mqw': 'popcorn',
    '1mqx': 'yay',
    '1mqy': 'feed',
    '1mqz': 'gomuscu',
    '1mr0': 'famoso',
    '1mr1': 'kebab',
  },
  'fluffy': {
    '1kl6': 'fete2',
    '1kl8': 'coeur2',
    '1klb': 'coeur3',
    '1kl1': 'koi',
    '1kl9': 'joue',
    '1kl7': 'cadeau',
    '1kl5': 'sleep3',
    '1kl2': 'heureux',
    '1kl3': 'blase',
    '1kky': 'dur2',
    '1kkz': 'dur3',
    '1kla': 'dur4',
    '1kl4': 'queue',
    '1kl0': 'nn',
  },
  'xmen': {
    '1mig-fr': 'xsalut',
    '1mij-fr': 'xwtf',
    '1mio': 'xmerci',
    '1mik': 'xaide',
    '1mih-fr': 'xprends',
    '1min': 'xwhy',
    '1mim': 'xjrv',
    '1mil': 'xcparti',
    '1mie-fr': 'xmv',
    '1mid-fr': 'xpptoi',
    '1mii-fr': 'xx',
    '1mif': 'xy',
    '1mip': 'xx2',
    '1miq': 'xy2',
    '1mir': 'xpub',
  }
}

module.exports = stickersList
